#!/usr/bin/env bash

# Set up a monorepo-style ternarykernels path for SGLang.
#
# This creates:
#   sglang/third_party/ternarykernels -> <source ternarykernels path>
#
# It also writes a lightweight env file:
#   sglang/.mangrove.env
#
# Usage:
#   ./util/setup_mangrove_monorepo.sh
#   ./util/setup_mangrove_monorepo.sh --source /home/ubuntu/ternarykernels --model-path /scratch/mangrove

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SGLANG_DIR="$(dirname "$SCRIPT_DIR")"

SOURCE_TERNARY="${SOURCE_TERNARY:-/home/ubuntu/ternarykernels}"
MODEL_PATH="${MANGROVE_MODEL_PATH:-/scratch/mangrove}"
FORCE=0

usage() {
  cat <<'EOF'
Usage: setup_mangrove_monorepo.sh [OPTIONS]

Options:
  --source <path>         Source ternarykernels repository path.
                          (default: /home/ubuntu/ternarykernels)
  --model-path <path>     Default production model path.
                          (default: /scratch/mangrove)
  --force                 Replace existing non-symlink path at third_party/ternarykernels.
  -h, --help              Show this help.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source)
      SOURCE_TERNARY="${2:-}"
      if [[ -z "${SOURCE_TERNARY}" ]]; then
        echo "Error: --source requires a value"
        exit 1
      fi
      shift 2
      ;;
    --model-path)
      MODEL_PATH="${2:-}"
      if [[ -z "${MODEL_PATH}" ]]; then
        echo "Error: --model-path requires a value"
        exit 1
      fi
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown argument: $1"
      usage
      exit 1
      ;;
  esac
done

if [[ ! -d "${SOURCE_TERNARY}/mangrove-turbo" ]]; then
  echo "Error: source path does not look like ternarykernels root:"
  echo "  ${SOURCE_TERNARY}"
  exit 1
fi

THIRD_PARTY_DIR="${SGLANG_DIR}/third_party"
LINK_PATH="${THIRD_PARTY_DIR}/ternarykernels"

mkdir -p "${THIRD_PARTY_DIR}"

if [[ -L "${LINK_PATH}" ]]; then
  current_target="$(readlink -f "${LINK_PATH}" || true)"
  source_target="$(readlink -f "${SOURCE_TERNARY}" || true)"
  if [[ "${current_target}" == "${source_target}" ]]; then
    echo "Monorepo link already configured:"
    echo "  ${LINK_PATH} -> ${current_target}"
  else
    ln -sfn "${SOURCE_TERNARY}" "${LINK_PATH}"
    echo "Updated link:"
    echo "  ${LINK_PATH} -> ${SOURCE_TERNARY}"
  fi
elif [[ -e "${LINK_PATH}" ]]; then
  if [[ "${FORCE}" -ne 1 ]]; then
    echo "Error: ${LINK_PATH} already exists and is not a symlink."
    echo "Use --force to replace it."
    exit 1
  fi
  rm -rf "${LINK_PATH}"
  ln -s "${SOURCE_TERNARY}" "${LINK_PATH}"
  echo "Replaced existing path with symlink:"
  echo "  ${LINK_PATH} -> ${SOURCE_TERNARY}"
else
  ln -s "${SOURCE_TERNARY}" "${LINK_PATH}"
  echo "Created link:"
  echo "  ${LINK_PATH} -> ${SOURCE_TERNARY}"
fi

ENV_FILE="${SGLANG_DIR}/.mangrove.env"
cat > "${ENV_FILE}" <<EOF
# Generated by util/setup_mangrove_monorepo.sh
export TERNARY_ROOT="${SOURCE_TERNARY}"
export MANGROVE_MODEL_PATH="${MODEL_PATH}"
export SGLANG_I2S_CUTLASS_LIB="${SGLANG_DIR}/libternary_cutlass_sm100.so"
EOF

echo
echo "Wrote ${ENV_FILE}"
echo "Next step:"
echo "  bash ${SGLANG_DIR}/util/build_sync_ternary_kernels.sh"
